name: Jest

on: [pull_request]

jobs:
  jest:
    name: Run Jest
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      checks: write
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Jest
        run: pnpm run test --ci --json --coverage --testLocationInResults --outputFile=./coverage/report.json

      - name: Upload Jest results as artifact (optional, but good for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: ./coverage/report.json

      - name: jest coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
